---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::hw_vm_tools'
    - 'role::hw_vm_tools:install'
    - 'role::hw_vm_tools:config'

- import_tasks: installation.yml
  tags:
    - 'role::hw_vm_tools'
    - 'role::hw_vm_tools:install'
